choco install -y 7zip.install
choco install -y vlc
choco install -y youtube-dl
choco install -y ffmpeg
choco install -y rufus
choco install -y qbittorrent
choco install -y powertoys
choco install -y everything
choco install -y k-litecodecpackfull